In [4]:
import numpy as np

In [5]:
arr1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2 = np.array([10, 20 ,30])

result = arr1 + arr2

print("Array1:")
print(arr1)
print("\nArray2:")
print(arr2)
print("\nResult of broadcasting:")
print(result)

Array1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array2:
[10 20 30]

Result of broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [6]:
val1 = np.mean(arr2)
print(arr2)
print(f"Average ousat value is {val1}")

[10 20 30]
Average ousat value is 20.0


In [7]:
val1 = np.max(arr2)
print(f"Max value is {val1}")

Max value is 30


In [8]:
val1 = np.min(arr2)
print(f"Min value is {val1}")

Min value is 10


In [9]:
arr3 = np.array([[1, 2, 3 ,4 ,5, 6], [7, 8, 9, 10, 11, 12]])
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
arr3.shape

(2, 6)

In [11]:
arr3 = arr3.reshape((3, 4))

In [12]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
x = np.arange(1, 10)

In [14]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
type(x)

numpy.ndarray

In [16]:
x = x.reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
y = np.arange(11,20)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
y = y.reshape((3,3))
y

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [19]:
z = x + y
z

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [20]:
x  = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x = np.zeros((3 ,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
x.dtype

dtype('float64')

In [23]:
x = np.zeros((3, 5), dtype='int32')
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
y = np.ones((3, 5),dtype='int32')
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
y = np.ones((3, 5), dtype='complex')
y

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [26]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [27]:
b = np.arange(1,3,0.1)
b

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [29]:
c = np.arange(1, 10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
c[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
c[1:5]

array([2, 3, 4, 5])

In [32]:
c[1:7]

array([2, 3, 4, 5, 6, 7])

In [33]:
c[1:9:2]

array([2, 4, 6, 8])

In [39]:
arr1 = np.array([[1, 2, 3, 11],[4, 5, 6,44],[7, 8, 9, 77]]) #3*3 array
arr2 = np.array([10, 20 ,30, 11, 66, 77, 91, 92, 188]) # 1D array

In [40]:
print(arr1)

[[ 1  2  3 11]
 [ 4  5  6 44]
 [ 7  8  9 77]]


In [42]:
arr1[0]

array([ 1,  2,  3, 11])

In [43]:
arr1[0][1]

2

In [44]:
arr1[::]

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 44],
       [ 7,  8,  9, 77]])

In [49]:
arr1[0:1]

array([[ 1,  2,  3, 11]])

In [50]:
arr1[0:2]

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 44]])

In [51]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [52]:
a = np.arange(1, 3, 0.1)
print(a)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9]


In [53]:
a = np.linspace(0, 3, 5)
a

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [61]:
a = np.linspace(0, 3, 15)
a

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [62]:
a = np.linspace(70, 90, 10)
a

array([70.        , 72.22222222, 74.44444444, 76.66666667, 78.88888889,
       81.11111111, 83.33333333, 85.55555556, 87.77777778, 90.        ])