In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2 = np.array([10, 20 ,30])

result = arr1 + arr2

print("Array1:")
print(arr1)
print("\nArray2:")
print(arr2)
print("\nResult of broadcasting:")
print(result)

Array1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array2:
[10 20 30]

Result of broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [3]:
val1 = np.mean(arr2)
print(arr2)
print(f"Average ousat value is {val1}")

[10 20 30]
Average ousat value is 20.0


In [4]:
val1 = np.max(arr2)
print(f"Max value is {val1}")

Max value is 30


In [5]:
val1 = np.min(arr2)
print(f"Min value is {val1}")

Min value is 10


In [6]:
arr3 = np.array([[1, 2, 3 ,4 ,5, 6], [7, 8, 9, 10, 11, 12]])
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
arr3.shape

(2, 6)

In [17]:
arr3 = arr3.reshape((3, 4))

In [18]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
x = np.arange(1, 10)

In [25]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
type(x)

numpy.ndarray

In [37]:
x = x.reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
y = np.arange(11,20)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
y = y.reshape((3,3))
y

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [38]:
z = x + y
z

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [40]:
x  = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x = np.zeros((3 ,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
x.dtype

dtype('float64')

In [45]:
x = np.zeros((3, 5), dtype='int32')
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [47]:
y = np.ones((3, 5),dtype='int32')
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
y = np.ones((3, 5), dtype='complex')
y

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [49]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [51]:
b = np.arange(1,3,0.1)
b

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [55]:
import pandas as pd