In [2]:
import numpy as np

In [3]:
#Exmple array
arr = np.array([10, 20, 30]) #1D array

In [4]:
arr

array([10, 20, 30])

In [5]:
arr.shape

(3,)

In [10]:
arr2 = np.array([[1, 2 ,3],[4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.size

6

In [11]:
arr2.shape

(2, 3)

In [14]:
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [15]:
arr3.shape

(2, 4)

In [16]:
arr3.size

8

In [17]:
# 2*4
new_array = np.array([[1, 2, 3 ,4 ],[5, 6, 7, 8]])
new_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
print(f"shape: {new_array.shape} size: {new_array.size}")

shape: (2, 4) size: 8


In [21]:
new_array.ndim

2

In [22]:
arr.ndim

1

In [24]:
arr4 = np.array([[[1,2],[3, 4]]])

In [26]:
print(arr4)

[[[1 2]
  [3 4]]]


In [27]:
arr4.shape

(1, 2, 2)

In [28]:
arr4.ndim

3

In [29]:
arr2.nbytes

24

In [30]:
arr2.dtype

dtype('int32')

In [32]:
new_array = np.array([
    [1.1, 2.2],
    [3.3, 4.4]
])

In [33]:
new_array

array([[1.1, 2.2],
       [3.3, 4.4]])

In [34]:
new_array.size

4

In [35]:
new_array.shape

(2, 2)

In [36]:
new_array.dtype

dtype('float64')

In [37]:
new_array.nbytes

32

In [38]:
new_array.ndim

2

In [44]:
new_array = np.array([[1.1, 2.2],[3.3, 4.4]], dtype='float32')
new_array

array([[1.1, 2.2],
       [3.3, 4.4]], dtype=float32)

In [43]:
new_array.nbytes

32

In [49]:
new_array = np.array([[1, 2],[3, 4]], dtype='int16')
new_array

array([[1, 2],
       [3, 4]], dtype=int16)

In [50]:
new_array.nbytes

8

In [51]:
new_array[0]

array([1, 2], dtype=int16)

In [52]:
new_array[0][0]

1